source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '8.0'
use_frameworks!

target 'LoveLimit' do
    pod 'Alamofire'
    pod 'Kingfisher','~>2.6'
    pod 'MJRefresh'
    pod 'SnapKit','~>0.22.0'
end
